DASOM-GitHub/dasom-web-backend

- .github/workflows/ci.yml
- .github/workflows/cicd.yml
- Dockerfile
- build.gradle
- src/main/resources/application-credentials.yml
- src/main/resources/application.yml
#5 
- Dockerfile 작성
- CI/CD 구현
- CI/CD workflow 작성
- CI workflow는 코드 통합(PR Merge) 이전에 오류를 검출하기 위함
- Docker 이미지 빌드에 경량화 된 베이스 이미지를 사용해 용량 최적화 (약 200MB 감소)
- 빌드 시 테스트 과정에서 dataSource 객체 생성 오류 발생; 테스트 환경에 h2 DB 의존성 추가
> [infra] CI/CD 파이프라인 구축

- src/main/java/dmu/dasom/api/global/auth/jwt/JwtUtil.java
- #9 
- 블랙리스트 저장 시 Redis 데이터 생명주기를 ms 단위로 저장하도록 변경
- 토큰 소유자(사용자) 이메일을 함께 저장하도록 구현
> [fix] 블랙리스트 토큰 저장 방식 수정

- src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantCreateRequestDto.java
- src/main/java/dmu/dasom/api/domain/applicant/entity/Applicant.java
- src/main/java/dmu/dasom/api/domain/applicant/enums/ApplicantStatus.java
- src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
- src/main/java/dmu/dasom/api/domain/common/exception/CustomControllerAdvice.java
- #13 
- Applicant 도메인 초기 구현
- 부원 지원 API 개발
- DTO, Entity 제약 조건 구성
- 추후 모집 일정 관리 기능 개발 후 모집 기간 검증 로직 추가 예정
> [feat] Applicant 도메인 구현

- Dockerfile
- #11 
- 서버 시간대, DB 시간대 설정을 KST로 통일해 시간대 관련한 문제 사전 차단
- Dockerfile 속 jar 실행 명령에 Asia/Seoul 시간대 설정 추가
> [infra] 서버 시간대 설정 추가

- src/main/java/dmu/dasom/api/global/auth/config/SecurityConfig.java
- #15 
- Security Config 속 CORS 설정 추가
- 모든 출처의 요청에 대한 CORS 허용 (추후 수정)
> [fix] CORS 개방 설정

- src/main/java/dmu/dasom/api/domain/google/service/GoogleApiService.java
- src/main/resources/application-credentials.yml
- googleApiService 빈의 의존성 주입 과정에서 실패하여 yml 파일에 있는 path 경로를 수정 devEnv파일에 google API json 추가
- googleApiService 빈의 의존성 주입 과정에서 실패하여 yml 파일에 있는 path 경로를 수정 devEnv파일에 google API json 추가
> [fix] Google 컨트롤러와 Google 서비스 간의 의존성 추가

- src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantDetailsResponseDto.java
- src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantResponseDto.java
- src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantStatusUpdateRequestDto.java
- src/main/java/dmu/dasom/api/domain/applicant/entity/Applicant.java
- src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
- src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
- src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
- src/main/java/dmu/dasom/api/global/admin/controller/AdminController.java
- src/main/java/dmu/dasom/api/global/dto/PageResponse.java
- src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
- #13 
- 어드민 페이지 지원자 관리용 API 개발
- 페이징 응답 전용 DTO 구현
- 지원자 조회 API 구현, 페이징 적용
- 지원자 상태 변경 API 구현
> [feat] 지원자 조회 API 구현

- src/main/java/dmu/dasom/api/domain/applicant/dto/ApplicantCreateRequestDto.java
- src/main/java/dmu/dasom/api/domain/applicant/entity/Applicant.java
- src/main/java/dmu/dasom/api/domain/applicant/repository/ApplicantRepository.java
- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
- src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
- src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
- src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
- #29 
- 지원자의 중복 지원을 막음
- 다시 지원할 경우 지원서 덮어쓰기 여부를 확인
- studentNo 필드에 `Unique` 제약조건 부여
- 덮어쓰기 여부를 클라이언트에서 확인 후 서버에게 다시 요청하는 방식
> [feat] 지원자 학번 중복 불가 설정

- src/main/java/dmu/dasom/api/domain/member/controller/MemberController.java
- src/main/java/dmu/dasom/api/domain/member/service/MemberServiceImpl.java
- src/main/java/dmu/dasom/api/global/auth/dto/TokenBox.java
- src/main/java/dmu/dasom/api/global/auth/filter/CustomAuthenticationFilter.java
- src/main/java/dmu/dasom/api/global/auth/jwt/JwtUtil.java
- #32 
- 클라이언트 자체적으로 접근 권한을 처리하기 위해 토큰 응답 시 사용자 권한도 같이 응답
- 응답 헤더로 사용자 권한 응답
- 쿠키로 응답시켜 위조를 방지하는 방식으로 추후 개선 필요
> [feat] 토큰 응답 시 사용자 권한 응답 추가

- src/main/java/dmu/dasom/api/domain/news/controller/NewsController.java
- src/main/java/dmu/dasom/api/domain/news/dto/NewsRequestDto.java
- src/main/java/dmu/dasom/api/domain/news/dto/NewsResponseDto.java
- src/main/java/dmu/dasom/api/domain/news/entity/NewsEntity.java
- src/main/java/dmu/dasom/api/domain/news/repository/NewsRepository.java
- src/main/java/dmu/dasom/api/domain/news/service/NewsService.java
- src/test/java/dmu/dasom/api/domain/news/NewsServiceTest.java
- #33 
- 다솜소식 조회, 등록 API 구현
- NewsRequest, ResponseDto
- Contoller
- Service
- Entity
- Repository
- 저,,, 무슨 문제인진 모르겠지만 redis가 제대로 설치가 안돼서 postman에서 못돌려봤습니다..... Windows에서 지원을 중단하였다고 하는데 해결방법 아시는 분 헬프 부탁드립니다.
> [feat] 다솜소식 API 구현

- src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
- src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
- src/main/java/dmu/dasom/api/domain/recruit/dto/RecruitConfigResponseDto.java
- src/main/java/dmu/dasom/api/domain/recruit/dto/RecruitScheduleModifyRequestDto.java
- src/main/java/dmu/dasom/api/domain/recruit/entity/Recruit.java
- src/main/java/dmu/dasom/api/domain/recruit/enums/ConfigKey.java
- src/main/java/dmu/dasom/api/domain/recruit/repository/RecruitRepository.java
- src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
- src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
- src/main/java/dmu/dasom/api/global/admin/controller/AdminController.java
- src/test/java/dmu/dasom/api/domain/recruit/RecruitServiceTest.java
- #27 
- 모집 일정 조회 API 구현
- 모집 일정 수정 API 구현 (어드민)
- 모집 일정을 Key:Value 타입으로 저장 및 관리하도록 구성
- 일정 수정 요청 시 요청 타입(key)에 맞게 날짜/시간 타입, 시간 타입 검증
- 관련 에러 코드 추가 및 Swagger 명세 추가
> [feat] 모집 일정 관리 API 구현

- src/main/java/dmu/dasom/api/domain/news/controller/NewsController.java
- #43 
- NewsController에 수정, 삭제가 기술이 안되어 있어 추가했습니다.
- 수정 -> PutMapping
- 삭제 -> DeleteMapping 사용해서 구현했습니다.
- 조회도 전체, 개별로 나눠봤습니다.
> [feat] 다솜소식 수정 삭제 명세서 추가

- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantService.java
- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
- src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
- src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
- src/main/java/dmu/dasom/api/domain/recruit/dto/ResultCheckRequestDto.java
- src/main/java/dmu/dasom/api/domain/recruit/dto/ResultCheckResponseDto.java
- src/main/java/dmu/dasom/api/domain/recruit/enums/ResultCheckType.java
- src/main/java/dmu/dasom/api/domain/recruit/service/RecruitService.java
- src/main/java/dmu/dasom/api/domain/recruit/service/RecruitServiceImpl.java
- src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
- src/test/java/dmu/dasom/api/domain/recruit/RecruitServiceTest.java
- #46 
- 서류, 최종 합격 조회 기능 구현
- 조회 타입에 따라 현재 조회 가능한지 여부 검증
- 학번으로 지원자 조회 로직 구현
- 학번으로 조회된 지원자의 연락처 뒷자리와 요청된 연락처 뒷자리가 일치한지 검증
- 서류, 최종 합격 조회 조건에 따라 현재 날짜가 합격 발표 기간 이후인지 검증하도록 구현
> [feat] 합격 조회 API 구현

- src/main/java/dmu/dasom/api/domain/applicant/service/ApplicantServiceImpl.java
- src/main/java/dmu/dasom/api/domain/google/service/GoogleApiService.java
- src/test/java/dmu/dasom/api/domain/applicant/ApplicantServiceTest.java
- #51 
- 지원자 상태 변경 시 구글 스프레드 시트에 해당 지원자 없으면 오류가 발생
- 지원자 상태 변경 시 DB에는 지원자가 존재하고 구글 스프레드 시트에 업데이트하는 로직 추가
- 지원자 상태 변경 시 DB에는 지원자가 존재하고 구글 스프레드 시트에 업데이트하는 로직 추가
- 지원자 상태 변경 시 DB에 지원자가 존재하고 구글 스프레드 시트에 없으면 업데이트하는 테스트 케이스 추가
> [fix] 지원자 상태 변경 오류

- src/main/java/dmu/dasom/api/global/healthcheck/HealthCheck.java
- #53 
- 서버 HealthCheck 구현
- 배포 스크립트 작성
- 엔드포인트에서 HTTP 200을 응답할 경우 서버 실행이 완료된 것으로 판단
- Blue/Green 배포 스크립트 작성(서버 내부)
> [infra] 무중단 배포 구성

- src/main/java/dmu/dasom/api/domain/interview/dto/InterviewSlotResponseDto.java
- #59 
- 면접 슬롯 조회시 슬롯 status 반환
- 면접 슬롯 조회시 슬롯 status 반환
- InterviewSlotResponseDto에 추가
> [fix] 면접 예약 API 면접 일정 조회시 status도 같이 반환

- src/main/java/dmu/dasom/api/domain/interview/dto/InterviewReservationApplicantResponseDto.java
- src/main/java/dmu/dasom/api/domain/interview/service/InterviewService.java
- src/main/java/dmu/dasom/api/domain/interview/service/InterviewServiceImpl.java
- src/main/java/dmu/dasom/api/domain/recruit/controller/RecruitController.java
- #59 
- 면접 예약자 명단 조회 API 추가
- 면접 예약자 명단 조회 API 추가
> [fix] 면접 예약 API 예약자 명단 조회 API 추가

- src/main/java/dmu/dasom/api/domain/interview/dto/InterviewReservationApplicantResponseDto.java
- src/main/java/dmu/dasom/api/domain/interview/dto/InterviewSlotResponseDto.java
- src/main/java/dmu/dasom/api/domain/interview/service/InterviewServiceImpl.java
- #59 
- 면접 예약자 조회시 면접시간, 면접일, 면접을 예약한 날짜와 시간을 반환
- InterviewReservationApplicantResponseDto에 면접시간, 면접일, 면접을 예약한 날짜와 시간 추가
> [fix] 면접 예약자 조회 API 면접일, 면접시간, 면접을 예약한 날짜와 시간 추가

- .github/workflows/ci.yml
- .github/workflows/cicd.yml
- #66 
- CI/CD 관련 의존성 캐싱으로 빌드, 배포시간 감소 효과 기대
- workflow 동작간 Gradle 의존성을 캐싱해 동작 시간을 감소시킴
> [infra] CI/CD 캐싱 도입

- src/main/java/dmu/dasom/api/domain/executive/dto/ExecutiveListResponseDto.java
- src/main/java/dmu/dasom/api/domain/executive/dto/ExecutiveRequestDto.java
- src/main/java/dmu/dasom/api/domain/executive/dto/ExecutiveResponseDto.java
- src/main/java/dmu/dasom/api/domain/executive/dto/ExecutiveUpdateRequestDto.java
- src/main/java/dmu/dasom/api/domain/executive/entity/ExecutiveEntity.java
- src/main/java/dmu/dasom/api/domain/executive/enums/Team.java
- src/main/java/dmu/dasom/api/domain/executive/service/ExecutiveServiceImpl.java
- src/test/java/dmu/dasom/api/domain/executive/service/ExecutiveServiceTest.java
- #98 
- 프론트엔드에서 요구하는 필드값으로 변경 및 enum 설정
- enum 부분  Team.enum 뿐만 아니라 Role.enum도 만들었는데 이것도 따로 뭐 추가해둬야할까용
> [refactor] 조직도 API 요청 파라미터 수정

- build.gradle
- src/main/java/dmu/dasom/api/domain/common/exception/ErrorCode.java
- src/main/java/dmu/dasom/api/global/R2/config/R2Config.java
- src/main/java/dmu/dasom/api/global/R2/service/R2Service.java
- src/main/java/dmu/dasom/api/global/admin/controller/AdminFileController.java
- src/main/java/dmu/dasom/api/global/file/dto/FileResponseDto.java
- src/main/java/dmu/dasom/api/global/file/entity/FileEntity.java
- src/main/java/dmu/dasom/api/global/file/service/FileService.java
- src/main/resources/application-credentials.yml
- #90 
- Cloudflare r2 스토리지와 연동하여 뉴스 생성시 이미지는 클라우드 스토리지에 업로드 하도록 변경
> [refactor] 이미지 저장 로직 수정
